apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: terraform-template
spec:
  templates:
  - name: terraform-template
    inputs:
      parameters:
      - name: app_repo
      - name: container_image
      - name: container_tag
    container:
      image: hashicorp/terraform:latest
      args:
      - --context={{inputs.parameters.app_repo}}
      - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
